Repository jenkinsci/JiraTestResultReporter-plugin, pull requests merged in 2024-10, with the labels that each got.

#161 Lower baseline to 2.452.3
  pom.xml
Labels: developer

#164 Format repository with Spotless
  pom.xml
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraIssueTrigger.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestData.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataRegistry.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/MetadataCache.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/TestToIssueMapping.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/VariableExpander.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/api/TestToIssueMappingApi.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/AbstractFields.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/Entry.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/FieldConfigsJsonAdapter.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableArrayFields.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableFields.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/StringArrayFields.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/StringFields.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/UserFields.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/restclientextensions/FullStatus.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/restclientextensions/FullStatusJsonParser.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/restclientextensions/JiraRestClientExtension.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/restclientextensions/StatusCategory.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/restclientextensions/StatusCategoryJsonParser.java
  src/test/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataTest.java
Labels: skip-changelog

#165 Add .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: skip-changelog

#159 Added bearer token support
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/BearerAuthenticationHandler.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
  src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/global.jelly
  src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/help-useBearerAuth.html
Labels: enhancement

#171 fix #143 java compiler warning
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableArrayFields.java
Labels: internal
