Repository jenkinsci/JiraTestResultReporter-plugin, pull requests merged in 2024-11, with the labels that each got.

#180 Test on Java 21
  .github/CODEOWNERS
  .gitignore
  Jenkinsfile
  pom.xml
Labels: skip-changelog

#182 [JENKINS-74234] Remove unused Jelly view
  src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/helpValidateConfigButton.jelly
Labels: removed

#181 [JENKINS-74233] Extract inline JavaScript from `JiraTestDataPublisher/config.jelly`
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
  src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/config.jelly
  src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/jira-test-data-publisher-resource.js
Labels: internal

#184 enable update to 3654.v237e4a_f2d8da_
  pom.xml
Labels: skip-changelog

#183 [JENKINS-74232][JENKINS-74235] Extract inline JavaScript
  src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction/badge.jelly
  src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction/helpIssueKeyInput.jelly
  src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction/resource.js
Labels: internal
