Repository jenkinsci/JiraTestResultReporter-plugin, pull requests merged in 2025-02, with the labels that each got.

#192 avoid some NPE on generateSnippet
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/TestToIssueMapping.java
Labels: enhancement

#207 Migrate from EE 8 to EE 9
  pom.xml
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/api/TestToIssueMappingApi.java
Labels: internal

#212 Avoid raw type warnings
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/MetadataCache.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/TestToIssueMapping.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/api/TestToIssueMappingApi.java
Labels: internal

#211 JENKINS-69312 JiraTestResultReporter plugin does not show plus button to create an issue
  README.md
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
  src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
  src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/config.jelly
  src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/help-manualAddIssue.html
Labels: bugfix
